# 服务器配置
[[servers]]
name = "161"
host = "192.168.1.161"
port = 22
user = "root"
identity_file = "/Users/kun/.ssh/id_rsa"

[[watchers]]
name = "api"
command = ""
watch = [
    "123"
]

# 任务1
[[tasks]]
name = "deploy_test"
target = "test_api"
build_command = "echo hi"
build_script_file = "./test/shell/test.sh"
deploy_server = ["161"]
deploy_path = "/app/mian"
deploy_script = "supervisor"
deploy_command = ""
#deploy_supervisor_file = "./supervisor.tpl"
pipeline = ["_"]





