# 服务器配置
[[servers]]
name = "161"
host = "192.168.1.161"
port = 22
user = "root"
identity_file = "/Users/kun/.ssh/id_rsa"

[[watchers]]
name = "api"
command = ""
watch = [
    "123"
]

# 任务1
[[tasks]]
name = "deploy_test"
build_command = "go build -o {{ workspace }}/test test/test.go"
build_script_file = "./test/shell/test.sh"
deploy_server = ["161"]
deploy_source = "{{ workspace }}/test"
deploy_path = "/app/nest/test"
deploy_script = "supervisor"
deploy_command = "touch /app/nest/hello.world"
deploy_script_file = "./test/shell/test.sh"
flow = ["_"]





