// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gozelle/gin"
	"github.com/koyeo/nest/hub/injector"
	"github.com/koyeo/nest/hub/internal/config"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(config2 *config.Config) (*gin.Engine, func(), error) {
	db, cleanup, err := injector.NewGormDB(config2)
	if err != nil {
		return nil, nil, err
	}
	publicAPI := injector.NewPublicAPI(db)
	privateAPI := injector.NewPrivateAPI(db)
	publisher := injector.NewPublisher(config2)
	engine := newApp(config2, db, publicAPI, privateAPI, publisher)
	return engine, func() {
		cleanup()
	}, nil
}
